In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [2]:
#importdataset 
#pemanggilan Dataset dengan nama Datanilai.csv
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[: ,:-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 nan]
 ['France' 37.0 67000.0]]


In [4]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [5]:
#Menghilangkan  missing value
from sklearn.impute import SimpleImputer
#missing values = nilai data yang digunakan sebagai penanda bahwa nilai aslinya tidak ada 
#strategy : menggunakan rata-rata kolom mean bisa juga menggunakan median, most_frequent(modus) atau constant
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [6]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 61375.0]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 61375.0]
 ['France' 37.0 67000.0]]


In [7]:
#Enconding Data kategori(Atribut)
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [8]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 61375.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 61375.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [9]:
#Encoding Data kategori(class/label)
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [11]:
#Membagi dataset ke dalam training set dan test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [12]:
print(x_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 61375.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 61375.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [13]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [14]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [15]:
print(y_test)

[0 1]


In [16]:
#Feature Scaling 
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [17]:
print(x_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0245464314521104]
 [0.0 1.0 0.0 -0.014117293757057777 -0.023360993551025323]
 [1.0 0.0 0.0 0.566708506533324 1.1113158360702047]
 [0.0 0.0 1.0 -0.30453019390224867 -0.06340841106706872]
 [0.0 0.0 1.0 -1.9018011447007988 -1.4517188849565736]
 [1.0 0.0 0.0 1.1475343068237058 1.858867629703015]
 [0.0 1.0 0.0 1.4379472069688968 -0.023360993551025323]
 [1.0 0.0 0.0 -0.7401495441200351 -0.38378775119541597]]


In [18]:
print(x_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.8109602046998791]
 [1.0 0.0 0.0 -0.44973664397484414 0.5773502691896258]]
