In [97]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [98]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[: ,:-1].values
y = dataset.iloc[:, -1].values

In [99]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 nan]
 ['France' 37.0 67000.0]]


In [100]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [102]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [103]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 59500.0]
 ['France' 35.0 58000.0]
 ['Spain' 38.0 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 59500.0]
 ['France' 37.0 67000.0]]


In [104]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [105]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 59500.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.0 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 59500.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [106]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [107]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [108]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [109]:
print(x_train)

[[0.0 0.0 1.0 38.0 52000.0]
 [0.0 1.0 0.0 40.0 59500.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 59500.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [110]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [111]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [112]:
print(y_test)

[0 1]


In [113]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [116]:
print(x_train)

[[0.0 0.0 1.0 -0.28942984211696865 -0.9697197789158528]
 [0.0 1.0 0.0 0.0 -0.17268982364254912]
 [1.0 0.0 0.0 0.5788596842339373 1.1556934351462902]
 [0.0 0.0 1.0 -0.28942984211696865 -0.013283832587888395]
 [0.0 0.0 1.0 -1.8812939737602963 -1.3948024217282815]
 [1.0 0.0 0.0 1.1577193684678746 1.8995880600680404]
 [0.0 1.0 0.0 1.4471492105848434 -0.17268982364254912]
 [1.0 0.0 0.0 -0.7235746052924217 -0.33209581469720983]]


In [117]:
print(x_test)

[[0.0 1.0 0.0 -1.4471492105848434 -0.7571784575096385]
 [1.0 0.0 0.0 -0.434144763175453 0.6243401316307545]]
