In [382]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [383]:
#importdataset 
#pemanggilan Dataset dengan nama Datanilaimhs.csv
dataset= pd.read_csv('Datanilaimhs.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values


In [384]:
print(X)

[['Budi' 92.0 3.0]
 ['Joko' 93.0 2.0]
 ['Iman' nan 2.0]
 ['Dwi' 85.0 1.0]
 ['Yudi' 96.0 2.0]
 ['Tama' 45.0 nan]
 ['Putri' nan 4.0]
 ['Rika' 72.0 3.0]]


In [385]:
print(y)

['Baik' 'Baik' 'Kurang' 'Baik' 'Baik' 'Kurang' 'Baik' 'Sedang']


In [386]:
#Menghilangkan  missing value
from sklearn.impute import SimpleImputer
#missing values = nilai data yang digunakan sebagai penanda bahwa nilai aslinya tidak ada 
#strategy : menggunakan rata-rata kolom mean bisa juga menggunakan median, most_frequent(modus) atau constant
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [387]:
print(X)

[['Budi' 92.0 3.0]
 ['Joko' 93.0 2.0]
 ['Iman' 80.5 2.0]
 ['Dwi' 85.0 1.0]
 ['Yudi' 96.0 2.0]
 ['Tama' 45.0 2.4285714285714284]
 ['Putri' 80.5 4.0]
 ['Rika' 72.0 3.0]]


In [388]:
#Enconding Data kategori(Atribut)
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers =[('encoder',OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [389]:
print(X)

[[1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 92.0 3.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 93.0 2.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 80.5 2.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 85.0 1.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 96.0 2.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 45.0 2.4285714285714284]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 80.5 4.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 72.0 3.0]]


In [390]:
#Encoding Data kategori(class/label)
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [391]:
print(y)

[0 0 1 0 0 1 0 2]


In [392]:
#Membagi dataset ke dalam training set dan test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, train_size = 0.8, random_state = 1)

In [393]:
print(X_train)


[[0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 93.0 2.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 80.5 4.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 92.0 3.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 96.0 2.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 85.0 1.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 45.0 2.4285714285714284]]


In [394]:
print(X_test)

[[0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 72.0 3.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 80.5 2.0]]


In [395]:
print(y_train)

[0 0 0 0 0 1]


In [396]:
print(y_test)

[2 1]


In [397]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [398]:
print(X_train)

[[0.0 0.0 0.0 2.2360679774997894 -0.44721359549995787 0.0
  -0.44721359549995787 -0.44721359549995787 0.6403933423679932
  -0.4347555938944297]
 [0.0 0.0 0.0 -0.44721359549995787 2.2360679774997894 0.0
  -0.44721359549995787 -0.44721359549995787 -0.081854788122225
  1.7134485171133411]
 [1.0 0.0 0.0 -0.44721359549995787 -0.44721359549995787 0.0
  -0.44721359549995787 -0.44721359549995787 0.5826134919287758
  0.6393464616094556]
 [0.0 0.0 0.0 -0.44721359549995787 -0.44721359549995787 0.0
  -0.44721359549995787 2.2360679774997894 0.8137328936856455
  -0.4347555938944297]
 [0.0 1.0 0.0 -0.44721359549995787 -0.44721359549995787 0.0
  -0.44721359549995787 -0.44721359549995787 0.17815453885425353
  -1.508857649398315]
 [0.0 0.0 0.0 -0.44721359549995787 -0.44721359549995787 0.0
  2.2360679774997894 -0.44721359549995787 -2.1330394787144447
  0.02557385846437813]]


In [399]:
print(X_test)

[[0.0 0.0 0.0 -0.44721359549995787 -0.44721359549995787 1.0
  -0.44721359549995787 -0.44721359549995787 -0.5729835168555734
  0.6393464616094556]
 [0.0 0.0 1.0 -0.44721359549995787 -0.44721359549995787 0.0
  -0.44721359549995787 -0.44721359549995787 -0.081854788122225
  -0.4347555938944297]]
