In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
#importdataset 
#pemanggilan Dataset dengan nama Datanilaimhs.csv
dataset= pd.read_csv('pengunjung_Mall.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values
print(X)

[[  1   1  19  15]
 [  2   1  21  15]
 [  3   2  20  16]
 [  4   2  23  16]
 [  5   2  31  17]
 [  6   2  22  17]
 [  7   2  35  18]
 [  8   2  23  18]
 [  9   1  64  19]
 [ 10   2  30  19]
 [ 11   1  67  19]
 [ 12   2  35  19]
 [ 13   2  58  20]
 [ 14   2  24  20]
 [ 15   1  37  20]
 [ 16   1  22  20]
 [ 17   2  35  21]
 [ 18   1  20  21]
 [ 19   1  52  23]
 [ 20   2  35  23]
 [ 21   1  35  24]
 [ 22   1  25  24]
 [ 23   2  46  25]
 [ 24   1  31  25]
 [ 25   2  54  28]
 [ 26   1  29  28]
 [ 27   2  45  28]
 [ 28   1  35  28]
 [ 29   2  40  29]
 [ 30   2  23  29]
 [ 31   1  60  30]
 [ 32   2  21  30]
 [ 33   1  53  33]
 [ 34   1  18  33]
 [ 35   2  49  33]
 [ 36   2  21  33]
 [ 37   2  42  34]
 [ 38   2  30  34]
 [ 39   2  36  37]
 [ 40   2  20  37]
 [ 41   2  65  38]
 [ 42   1  24  38]
 [ 43   1  48  39]
 [ 44   2  31  39]
 [ 45   2  49  39]
 [ 46   2  24  39]
 [ 47   2  50  40]
 [ 48   2  27  40]
 [ 49   2  29  40]
 [ 50   2  31  40]
 [ 51   2  49  42]
 [ 52   1  33  42]
 [ 53   2  3